### ISSUE TITLE
[Issue] Users with lots of locks have trouble calling commands due to Discord character limits

### ISSUE THREAD

**Issue by KevinCrossDCL** [rileyio/kiera-bot#27]
**Describe the issue/bug**
It would seem that running commands like !ck stats lockee LockeeName or !ck debug LockeeName have problems when the lockee has a lot of locks active. Like close to 20 say. This is as you've said due to character limits in a single message that Discord have put in place.

**Additional context**
My suggestion was to only show the first 10 locks in the users list. And you suggested adding an extra parameter that would let them choose a range of 10 i.e. 5-10

The discussion we had starts here on Discord: https://discordapp.com/channels/473856867768991744/535890258357649428/705497895297613824

**Comment by rileyio** [comment]
Tackled this in b498d1d2dda332599126647c28a4b1d2d7027fa2 - Limiting the user at this time to the first 5 locks.

Will review again in upcoming releases having a range that a user can specify to see other locks beyond the initial 5.  I will track this on a Feature request.
