### ISSUE TITLE
!ck ticker returns php attachment

### ISSUE THREAD

**Issue by bdsm-spuddy** [rileyio/kiera-bot#34]
DM to Kiera "!ck ticker"

Result is an attachment "ticker.php"

The attachment _is_ an image:

PNG image data, 400 x 80, 8-bit/color RGB, non-interlaced

The content is correct (earlier test returned "null" user, but later test returned correct details, so may have been before caching after restart?).

So it may just be content type issue.

**Comment by rileyio** [comment]
Fixed & will be included in `6.0.0-beta-2`
