### ISSUE TITLE
[Bug] Fetching Status of Chastisafe Data

### ISSUE THREAD

**Issue by Johanna-5** [rileyio/kiera-bot#77]
Users without any Chastisafe data will have a error when using Kiera Update or Lookup command.
You can stop that by checking the Status in the Data which tells you if something went wrond during lookup.
data[status] = 0 -> everything worked fine
data[status != 0 -> error (written in reason)
![Screenshot_1](https://user-images.githubusercontent.com/82082894/195546055-af4ef630-386a-4630-a911-97cc8409e45e.png)

**Comment by rileyio** [comment]
I will be assigning this to a version milestone to get it sorted in an upcoming release.
Sorry for the delay in handling.
